### ISSUE TITLE
Support containerd config_path for registry endpoints

### ISSUE THREAD

**Issue by brandond** [containerd/stargz-snapshotter#1647]
Containerd has preferred using docker-style `certs.d` via the  CRI `config_path` values, since the 1.5 release.
Ref: https://github.com/containerd/containerd/blob/main/docs/hosts.md#cri
```toml
[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "/etc/containerd/certs.d"
```

stargz should support this, instead of requiring inline config under the `plugins."io.containerd.snapshotter.v1.stargz".registry.mirrors` table key

Current:
```toml
[plugins."io.containerd.snapshotter.v1.stargz".registry.mirrors."docker.io"]
  endpoint = ["https://registry.example.com/v2"]
```

Preferred:
```toml
[plugins."io.containerd.snapshotter.v1.stargz".registry]
  config_path = "/etc/containerd/certs.d"
```
