### ISSUE TITLE
Custom remote snapshotter does not receive enough information when `Mount` is called

### ISSUE THREAD

**Issue by aochagavia** [containerd/stargz-snapshotter#1834]
I'm trying out the "Make your remote snapshotter" feature, mentioned in the [overview](https://github.com/containerd/stargz-snapshotter/blob/01fd6675811429ce3bed088b1ae9d8274fd8d957/docs/overview.md#make-your-remote-snapshotter), but I can't get it working. 

### Context

Here's what I've done:

1. Create a type that implements the `FileSystem` interface (with `Mount`, `Check` and `Unmount` functions) and expose it through a gRPC server on `unix:///dev/shm/test-snapshotter.sock`.
2. Configure containerd's `config.toml`, registering the snapshotter under the name `mysnap`:

    ```toml
    [proxy_plugins]
      [proxy_plugins.mysnap]
        type = "snapshot"
        address = "/dev/shm/test-snapshotter.sock"
    ```
3. Run `nerdctl pull debian --snapshotter mysnap`

### Problem

Directly after `nerdctl pull`, the snapshotter receives a call to `Mount`. However, the only provided label is `containerd.io/snapshot.ref`, which is not enough enough information to retrieve the remote layer.

### Additional details

Note that, if I pull using `crictl pull`, I do receive additional labels such as `containerd.io/snapshot/cri.layer-digest`.
